---
title: "sEEG Coherence Analysis"
author: "Xianqing"
date: "6/28/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=3)# all numeric output gets rounded to 3 dp
library(tidyverse)
library(patchwork)
library(lme4)
library(lmerTest)
library(broom.mixed)
library(DHARMa)
library(sjPlot)
library(lmeresampler)
library(merTools)
library(pander)
source("https://uoepsy.github.io/msmr/functions/code_poly.R") # Dan's code
load("C:/Users/xjl19/Desktop/sEEG coherence/sEEG Coherence Analysis/plvRdata.RData")
```

## 1. PREPROCESS PLV DATA

```{r Combine datasets}
filelist.theta <- list.files(".\\4-7")
filelist.alpha <- list.files(".\\8-12")
filelist.gamma <- list.files(".\\70-150")

for (i in 1:length(filelist.theta)){
  current_theta <- read.csv(paste0(".\\4-7\\", filelist.theta[i]))
  current_alpha <- read.csv(paste0(".\\8-12\\", filelist.alpha[i]))
  current_gamma <- read.csv(paste0(".\\70-150\\", filelist.gamma[i]))
  
  if (i == 1) {
    plv_theta <- current_theta
    plv_alpha <- current_alpha
    plv_gamma <- current_gamma
    
  } else {
    plv_theta <- rbind(plv_theta, current_theta)
    plv_alpha <- rbind(plv_alpha, current_alpha)
    plv_gamma <- rbind(plv_gamma, current_gamma)
  }
}

# baseline_theta <- filter(plv_theta, TimeBin < 6)
# baseline_alpha <- filter(plv_alpha, TimeBin < 6)
# baseline_gamma <- filter(plv_gamma, TimeBin < 6)
# qplot(plv_theta$PLV, bins=20) / qplot(baseline_theta$PLV, bins=20)
# qplot(plv_alpha$PLV, bins=20) / qplot(baseline_alpha$PLV, bins=20)
# qplot(plv_gamma$PLV, bins=20) / qplot(baseline_gamma$PLV, bins=20)
```

```{r Add ROI info}
#Add 1st Channel ROI info 
# plv_theta <- plv_theta %>%
# plv_alpha <- plv_alpha %>%
plv_gamma <- plv_gamma %>%
  mutate(ROI_1=ifelse(AAL_1 == "Temporal_Pole_Mid_L" | # ATL ROI definition
                        AAL_1 == "Temporal_Pole_Mid_R" |
                        AAL_1 == "Temporal_Pole_Sup_L"| 
                        AAL_1 == "Temporal_Pole_Sup_R" |
                        HarvardOxford_1 == "tissue 8" |
                        Destrieux_1== "ctx_lh_Pole_temporal" |
                        Destrieux_1 == "ctx_rh_Pole_temporal", "ATL",
                      ifelse(AAL_1 == "SupraMarginal_L" | # IPL ROI definition
                               AAL_1 == "SupraMarginal_R" |
                               AAL_1 == "Angular_L" |
                               AAL_1 == "Angular_R" |
                               DesikanKilliany_1 == "ctx-lh-supramarginal" |
                               DesikanKilliany_1 == "ctx-rh-supramarginal", "IPL",
                             ifelse(HarvardOxford_1 == "tissue 12" |
                                      HarvardOxford_1 == "tissue 13", "pMTG",
                                    ifelse(AFNI_1 == "Inferior Frontal Gyrus" | # IFG ROI definition
                                             substring(Brainnetome_1, 1, 3) == "IFG" |
                                             AAL_1 == "Frontal_Inf_Tri_L" |
                                             AAL_1 == "Frontal_Inf_Tri_R" |
                                             AAL_1 == "Frontal_Inf_Orb_L" |
                                             AAL_1 == "Frontal_Inf_Orb_R" |
                                             AAL_1 == "Frontal_Inf_Oper_L" |
                                             AAL_1 == "Frontal_Inf_Oper_R", "IFG", "NA"))))) %>%
  mutate(ROI_2=ifelse(AAL_2 == "Temporal_Pole_Mid_L" | # ATL ROI definition
                        AAL_2 == "Temporal_Pole_Mid_R" |
                        AAL_2 == "Temporal_Pole_Sup_L"| 
                        AAL_2 == "Temporal_Pole_Sup_R" |
                        HarvardOxford_2 == "tissue 8" |
                        Destrieux_2== "ctx_lh_Pole_temporal" |
                        Destrieux_2 == "ctx_rh_Pole_temporal", "ATL",
                      ifelse(AAL_2== "SupraMarginal_L" | # IPL ROI definition
                               AAL_2 == "SupraMarginal_R" |
                               AAL_2 == "Angular_L" |
                               AAL_2 == "Angular_R" |
                               DesikanKilliany_2 == "ctx-lh-supramarginal" |
                               DesikanKilliany_2 == "ctx-rh-supramarginal", "IPL",
                             ifelse( HarvardOxford_2 == "tissue 12" |
                                       HarvardOxford_2 == "tissue 13", "pMTG",
                                     ifelse(AFNI_2 == "Inferior Frontal Gyrus" | # IFG ROI definition
                                              substring(Brainnetome_2, 1, 3) == "IFG" |
                                              AAL_2 == "Frontal_Inf_Tri_L" |
                                              AAL_2 == "Frontal_Inf_Tri_R" |
                                              AAL_2 == "Frontal_Inf_Orb_L" |
                                              AAL_2 == "Frontal_Inf_Orb_R" |
                                              AAL_2 == "Frontal_Inf_Oper_L" |
                                              AAL_2 == "Frontal_Inf_Oper_R", "IFG", "NA")))))
# write.csv(plv_theta, "PLV_alldata_4-7Hz.csv")
# write.csv(plv_alpha, "PLV_alldata_8-12Hz.csv")
write.csv(plv_gamma, "PLV_alldata_70-150Hz.csv")
```

```{r Baseline correction}
plv_theta <- read.csv("PLV_alldata_4-7Hz.csv")
plv_alpha <- read.csv("PLV_alldata_8-12Hz.csv")
plv_gamma <- read.csv("PLV_alldata_70-150Hz.csv")
plv_theta <- plv_theta[,-1]
plv_alpha <- plv_alpha[,-1]
plv_gamma <- plv_gamma[,-1]

plv_theta <- plv_theta[plv_theta$Artifact == 0, c(1:7,14,21:25)]
plv_alpha <- plv_alpha[plv_alpha$Artifact == 0, c(1:7,14,21:25)]
plv_gamma <- plv_gamma[plv_gamma$Artifact == 0, c(1:7,14,21:25)]
summary(plv_theta)
summary(plv_alpha)
summary(plv_gamma)



plv_theta <- plv_theta %>% mutate(ChannelPair = paste(Channel_1, Channel_2, sep = "-"),
                                  ItemPair = paste(Item_1, Item_2, sep = "-"))
plv_alpha <- plv_alpha %>% mutate(ChannelPair = paste(Channel_1, Channel_2, sep = "-"),
                                  ItemPair = paste(Item_1, Item_2, sep = "-"))
plv_gamma <- plv_gamma %>% mutate(ChannelPair = paste(Channel_1, Channel_2, sep = "-"),
                                  ItemPair = paste(Item_1, Item_2, sep = "-"))

# Baseline Correction (by subtraction mean)
baseline_theta <- filter(plv_theta, TimeBin < 6) %>%
  group_by(Subject, TrialNumber, ChannelPair) %>%
  summarise(baseline = mean(PLV))
baseline_alpha <- filter(plv_alpha, TimeBin < 6) %>%
  group_by(Subject, TrialNumber, ChannelPair) %>%
  summarise(baseline = mean(PLV))
baseline_gamma <- filter(plv_gamma, TimeBin < 6) %>%
  group_by(Subject, TrialNumber, ChannelPair) %>%
  summarise(baseline = mean(PLV))

# # Baseline Correction (by subtraction median)
# baseline_theta <- filter(plv_theta, TimeBin < 6) %>% 
#   group_by(Subject, TrialNumber, ChannelPair) %>% 
#   summarise(baseline = median(PLV))
# baseline_alpha <- filter(plv_alpha, TimeBin < 6) %>% 
#   group_by(Subject, TrialNumber, ChannelPair) %>% 
#   summarise(baseline = median(PLV))
# baseline_gamma <- filter(plv_gamma, TimeBin < 6) %>% 
#   group_by(Subject, TrialNumber, ChannelPair) %>% 
#   summarise(baseline = median(PLV))

plv_theta <- plv_theta %>% filter(TimeBin > 5) %>% left_join(baseline_theta)
plv_alpha <- plv_alpha %>% filter(TimeBin > 5) %>% left_join(baseline_alpha)
plv_gamma <- plv_gamma %>% filter(TimeBin > 5) %>% left_join(baseline_gamma)
plv_theta$corrected_PLV <- plv_theta$PLV - plv_theta$baseline
plv_alpha$corrected_PLV <- plv_alpha$PLV - plv_alpha$baseline
plv_gamma$corrected_PLV <- plv_gamma$PLV - plv_gamma$baseline


plv_theta$corrected_PLV <- plv_theta$PLV / plv_theta$baseline
plv_alpha$corrected_PLV <- plv_alpha$PLV / plv_alpha$baseline
plv_gamma$corrected_PLV <- plv_gamma$PLV / plv_gamma$baseline



# summary(plv_theta)
# summary(plv_alpha)
# summary(plv_gamma)

write.csv(plv_theta, "PLV_anadata_4-7Hz_sub.csv")
write.csv(plv_alpha, "PLV_anadata_8-12Hz_sub.csv")
write.csv(plv_gamma, "PLV_anadata_70-150Hz_sub.csv")

write.csv(plv_theta, "PLV_anadata_4-7Hz_div.csv")
write.csv(plv_alpha, "PLV_anadata_8-12Hz_div.csv")
write.csv(plv_gamma, "PLV_anadata_70-150Hz_div.csv")
```

## 2. ANALYSE PLV DATA

```{r Prepare datasets (ROI x Frequency)}
plv_theta <- read.csv("PLV_anadata_4-7Hz_sub.csv")
plv_alpha <- read.csv("PLV_anadata_8-12Hz_sub.csv")
plv_gamma <- read.csv("PLV_anadata_70-150Hz_sub.csv")

# plv_theta <- read.csv("PLV_anadata_4-7Hz_div.csv")
# plv_alpha <- read.csv("PLV_anadata_8-12Hz_div.csv")
# plv_gamma <- read.csv("PLV_anadata_70-150Hz_div.csv")

# theta band
ATL_theta <- plv_theta %>% filter(ROI_1=="ATL" & ROI_2=="ATL")
IPL_theta <- plv_theta %>% filter(ROI_1=="IPL" & ROI_2=="IPL")
IFG_theta <- plv_theta %>% filter(ROI_1=="IFG" & ROI_2=="IFG")
pMTG_theta <- plv_theta %>% filter(ROI_1=="pMTG" & ROI_2=="pMTG")

# alpha band
ATL_alpha <- plv_alpha %>% filter(ROI_1=="ATL" & ROI_2=="ATL")
IPL_alpha <- plv_alpha %>% filter(ROI_1=="IPL" & ROI_2=="IPL")
IFG_alpha <- plv_alpha %>% filter(ROI_1=="IFG" & ROI_2=="IFG")
pMTG_alpha <- plv_alpha %>% filter(ROI_1=="pMTG" & ROI_2=="pMTG")

# gamma band
ATL_gamma <- plv_gamma %>% filter(ROI_1=="ATL" & ROI_2=="ATL")
IPL_gamma <- plv_gamma %>% filter(ROI_1=="IPL" & ROI_2=="IPL")
IFG_gamma <- plv_gamma %>% filter(ROI_1=="IFG" & ROI_2=="IFG")
pMTG_gamma <- plv_gamma %>% filter(ROI_1=="pMTG" & ROI_2=="pMTG")
```

```{r Plot and check for condition effect}
# theta band
th_ATL <- ggplot(ATL_theta, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  ylab("Theta-band corrected PLV")+
  ggtitle("ATL")+
  theme_classic()+
  theme(legend.position="none", axis.title.x=element_blank())
# th_ATL

th_IPL <- ggplot(IPL_theta, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  ggtitle("IPL")+
  theme_classic()+
  theme(legend.position="none", axis.title.x=element_blank(), axis.title.y=element_blank())
# th_IPL

th_IFG <- ggplot(IFG_theta, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  ggtitle("IFG")+
  theme_classic()+
  theme(legend.position="none", axis.title.x=element_blank(), axis.title.y=element_blank())
# th_IFG

th_pMTG <- ggplot(pMTG_theta, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  ggtitle("pMTG")+
  theme_classic()+
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
# th_pMTG

# alpha band
al_ATL <- ggplot(ATL_alpha, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  ylab("Alpha-band corrected PLV")+
  theme_classic()+
  theme(legend.position="none", axis.title.x=element_blank())
# al_ATL

al_IPL <- ggplot(IPL_alpha, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  theme_classic()+
  theme(legend.position="none", axis.title.x=element_blank(), axis.title.y=element_blank())
# al_IPL

al_IFG <- ggplot(IFG_alpha, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  theme_classic()+
  theme(legend.position="none", axis.title.x=element_blank(), axis.title.y=element_blank())
# al_IFG

al_pMTG <- ggplot(pMTG_alpha, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  theme_classic()+
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
# al_pMTG

# gamma band
ga_ATL <- ggplot(ATL_gamma, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time Bin")+
  ylab("Gamma-band corrected PLV")+
  theme_classic()+
  theme(legend.position="none")
# ga_ATL

ga_IPL <- ggplot(IPL_gamma, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time Bin")+
  theme_classic()+
  theme(legend.position="none", axis.title.y=element_blank())
# ga_IPL

ga_IFG <- ggplot(IFG_gamma, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time Bin")+
  theme_classic()+
  theme(legend.position="none", axis.title.y=element_blank())
# ga_IFG

ga_pMTG <- ggplot(pMTG_gamma, aes(x=TimeBin-5, y=corrected_PLV, col=Condition))+
  stat_summary(geom="pointrange")+
  geom_smooth(aes(col=Condition, fill=Condition), alpha=.1)+
  # stat_summary(geom="line")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time Bin")+
  theme_classic()+
  theme(axis.title.y=element_blank())
# ga_pMTG

(th_ATL | th_IPL | th_IFG | th_pMTG)  / (al_ATL | al_IPL | al_IFG | al_pMTG)  / (ga_ATL | ga_IPL | ga_IFG | ga_pMTG)
```

### theta

```{r Model ATL theta}
# ATL theta linear -------------------------------------------------------
ATL_theta <- ATL_theta %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.ATL_theta <- lmer(corrected_PLV ~ centered_timebin*Condition +  
                      (1 | ItemPair) + (1 | Subject) + (1 + Condition | ChannelPair:Subject),
                    data = ATL_theta, REML = F, control = lmerControl(optimizer="bobyqa"))
summary(m.ATL_theta)

# # bootstrap
# bs1.ATL_theta <- bootstrap(m.ATL_theta, .f=fixef, type="case", B=100, resample=c(T,F,F))
# bs2.ATL_theta <- bootstrap(m.ATL_theta, .f=fixef, type="case", B=10, resample=c(F,T,F))
# CI.ATL_theta <- confint(bs1.ATL_theta, type="perc")
# CI.ATL_theta
# 
# ATL_theta_pInterval <- predictInterval(merMod = m.ATL_theta, newdata = ATL_theta, level = 0.95, n.sims = 1000, stat = "mean", type = "linear.prediction")
# summary(ATL_theta_pInterval)
# 
# cbind(ATL_theta, ATL_theta_pInterval) %>% 
#   group_by(Condition, TimeBin) %>% 
#   summarise(fit = mean(fit), upr = mean(upr), lwr = mean(lwr)) %>% 
#   ggplot(aes(x=TimeBin, y=fit, col=Condition))+
#   geom_line(size = 1.5)+
#   geom_hline(yintercept = 0, linetype="dashed")+
#   # stat_summary(aes(y = fitted(m.ATL_theta)), geom = "line")+
#   geom_ribbon(aes(ymin=lwr, ymax=upr, fill=Condition), alpha=.1, color=F)+
#   theme_bw()

# # test influence
# library(influence.ME)
# m.ATL_theta_sub <- influence(m.ATL_theta, "Subject")
# m.ATL_theta_trl <- influence(m.ATL_theta, "ItemPair")
# plot(m.ATL_theta_sub, which="cook", cutoff=.15, sort=TRUE, 
#      xlab="Cook´s Distance", ylab="Subject")
# plot(m.ATL_theta_trl, which="cook", cutoff=.15, sort=TRUE, 
#      xlab="Cook´s Distance", ylab="Trial")

## plot model fit
fit.ATL_theta <- ATL_theta %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.ATL_theta)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("ATL_theta")+
  theme_bw()
fit.ATL_theta

## test assumptions
simulateResiduals(fittedModel = m.ATL_theta, plot = T)
plot_model(m.ATL_theta, "diag")
dotplot.ranef.mer(ranef(m.ATL_theta, condVar=T))

x<-rnorm(3000,0,1)
funss<-function(x) 1/sqrt(2*pi)*exp(-1/2*x^2)

ATL_theta %>% mutate(residual1 = corrected_PLV - fitted(m.ATL_theta)) %>% 
  ggplot(aes(x = residual1, col=Condition, fill=Condition))+
  geom_density(alpha=.3)+
  theme_classic()
  
# ATL theta polynomial -------------------------------------------------------
ATL_theta <- code_poly(ATL_theta, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.ATL_theta3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (1 | ItemPair) + (1 + Condition | Subject/ChannelPair),
                    data = ATL_theta, control = lmerControl(optimizer="bobyqa"))
summary(m.ATL_theta3)
## plot model fit
fit.ATL_theta3 <- ATL_theta %>% 
  ggplot(aes(x = TimeBin-5, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.ATL_theta3)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("ATL_theta3")+
  theme_bw()
fit.ATL_theta3
## test assumptions
simulateResiduals(fittedModel = m.ATL_theta3, plot = T)
plot_model(m.ATL_theta3, "diag")
dotplot.ranef.mer(ranef(m.ATL_theta3, condVar=T))

# loop ATL_theta  -------------------------------------------------------
coef_ATL_theta <- data.frame()
for (i in 6:25){
  ATL_theta_timebin <- filter(ATL_theta, TimeBin == i)
  m.ATL_theta_timebin <- lmer(corrected_PLV ~ Condition
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair),
                              data = ATL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.ATL_theta_timebin) == 1){
    m.ATL_theta_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) +
                                (1 | ChannelPair:Subject) + (1 | ItemPair),
                              data = ATL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.ATL_theta_timebin) == 1){
    m.ATL_theta_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair),
                              data = ATL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.ATL_theta_timebin) == 1){
    m.ATL_theta_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair),
                              data = ATL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.ATL_theta_timebin) == 1){
    ranef <- "-"
  }
  coef_new <-
    summary(m.ATL_theta_timebin)$coefficients %>%
    data.frame() %>% mutate(TimeBin = i, rand_eff = ranef)
  coef_ATL_theta <- bind_rows(coef_ATL_theta,coef_new)
}

coef_ATL_theta <- data.frame()
for (i in 6:25){
  ATL_theta_timebin <- filter(ATL_theta, TimeBin == i)
  m.ATL_theta_timebin <- lmer(corrected_PLV ~ Condition + (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = ATL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
  coef_new <- 
    summary(m.ATL_theta_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i)
  coef_ATL_theta <- bind_rows(coef_ATL_theta,coef_new)
}

slope_ATL_theta <- coef_ATL_theta[seq(0,nrow(coef_ATL_theta),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.08, 0, 1))

beta.ATL_theta <- slope_ATL_theta %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+ geom_hline(yintercept=0, linetype="dashed")+
  ylim(-.1, .07) + xlab("Time window (100ms)") + ylab("Beta (TX-Thm)")+
  ggtitle("ATL_theta") + theme_classic()
beta.ATL_theta
```

```{r Model IPL theta}
# IPL theta linear -------------------------------------------------------
IPL_theta <- IPL_theta %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.IPL_theta <- lmer(corrected_PLV ~  centered_timebin * Condition +
                      (1 | ItemPair) + (1 | Subject) + (1 + Condition | ChannelPair:Subject),
                    data = IPL_theta, REML=T, control = lmerControl(optimizer="bobyqa"))
summary(m.IPL_theta)
## plot model fit
fit.IPL_theta <- IPL_theta %>% 
  ggplot(aes(x = TimeBin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.IPL_theta)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IPL_theta")+ 
  theme_bw()
fit.IPL_theta

## test assumptions
simulateResiduals(fittedModel = m.IPL_theta, plot = T)
plot_model(m.IPL_theta, "diag")
dotplot.ranef.mer(ranef(m.IPL_theta, condVar=T))

# IPL theta polynomial -------------------------------------------------------
IPL_theta <- code_poly(IPL_theta, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.IPL_theta3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) + (0 + poly1 + poly3 | Subject),
                    data = IPL_theta, control = lmerControl(optimizer="bobyqa"))
summary(m.IPL_theta3)

## plot model fit
fit.IPL_theta3 <- IPL_theta %>% 
  ggplot(aes(x = TimeBin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.IPL_theta3)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IPL_theta3")+
  theme_bw()
fit.IPL_theta3

## test assumptions
simulateResiduals(fittedModel = m.IPL_theta3, plot = T)
plot_model(m.IPL_theta3, "diag")
dotplot.ranef.mer(ranef(m.IPL_theta3, condVar=T))

# loop IPL_theta -------------------------------------------------------
coef_IPL_theta <- data.frame()
for (i in 6:25){
  IPL_theta_timebin <- filter(IPL_theta, TimeBin == i)
  m.IPL_theta_timebin <- lmer(corrected_PLV ~ Condition
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair),
                              data = IPL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.IPL_theta_timebin) == 1){
    m.IPL_theta_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) +
                                (1 | ChannelPair:Subject) + (1 | ItemPair),
                              data = IPL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.IPL_theta_timebin) == 1){
    m.IPL_theta_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair),
                              data = IPL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.IPL_theta_timebin) == 1){
    m.IPL_theta_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair),
                              data = IPL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.IPL_theta_timebin) == 1){
    m.IPL_theta_timebin <- lmer(corrected_PLV ~ Condition +  (1 | ItemPair),
                              data = IPL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.IPL_theta_timebin) == 1){
    ranef <- "-"
  }
  coef_new <-
    summary(m.IPL_theta_timebin)$coefficients %>%
    data.frame() %>%
    mutate(TimeBin = i, rand_eff = ranef)
  coef_IPL_theta <- bind_rows(coef_IPL_theta,coef_new)
}

coef_IPL_theta <- data.frame()
for (i in 6:25){
  IPL_theta_timebin <- filter(IPL_theta, TimeBin == i)
  m.IPL_theta_timebin <- lmer(corrected_PLV ~ Condition + (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = IPL_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
  coef_new <- 
    summary(m.IPL_theta_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i)
  coef_IPL_theta <- bind_rows(coef_IPL_theta,coef_new)
}

# check significant slope
slope_IPL_theta <- coef_IPL_theta[seq(0,nrow(coef_IPL_theta),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

# betaplot with sig time windows
beta.IPL_theta <- slope_IPL_theta %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=5, xmax=6,
           ymin=-.1, ymax=.07, alpha=.3, fill="red")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("IPL_theta")+
  theme_classic()
beta.IPL_theta
```

```{r Model IFG theta}
# IFG theta linear --------------
IFG_theta <- IFG_theta %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.IFG_theta <- lmer(corrected_PLV ~ centered_timebin * Condition +
                      (1 | ItemPair) + (1 | Subject) +  (1 + Condition | ChannelPair:Subject),
                    data = IFG_theta, REML=T, control = lmerControl(optimizer="bobyqa"))
summary(m.IFG_theta)

## plot model fit
fit.IFG_theta <- IFG_theta %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.IFG_theta)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IFG_theta")+
  theme_bw()
fit.IFG_theta

## test assumptions
simulateResiduals(fittedModel = m.IFG_theta, plot = T)
plot_model(m.IFG_theta, "diag")
dotplot.ranef.mer(ranef(m.IFG_theta, condVar=T))

# IFG theta polynomial ------
IFG_theta <- code_poly(IFG_theta, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.IFG_theta3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) +
                       (poly1 + poly2 + poly3 + Condition | Subject),
                    data = IFG_theta, control = lmerControl(optimizer="bobyqa"))
summary(m.IFG_theta3)

## plot model fit
fit.IFG_theta3 <- augment(m.IFG_theta3) %>% 
  ggplot(aes(x = poly1, y = .fitted, col = Condition))+
  stat_summary(geom="line")+
  geom_hline(yintercept = 0, linetype = "dashed")+
  theme_classic()
fit.IFG_theta3
## test assumptions
simulateResiduals(fittedModel = m.IFG_theta3, plot = T)
plot_model(m.IFG_theta3, "diag")
dotplot.ranef.mer(ranef(m.IFG_theta3, condVar=T))

# loop IFG_theta  -------------------------------------------------------
coef_IFG_theta <- data.frame()
for (i in 6:25){
  IFG_theta_timebin <- filter(IFG_theta, TimeBin == i)
  m.IFG_theta_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = IFG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.IFG_theta_timebin) == 1){
    m.IFG_theta_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = IFG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.IFG_theta_timebin) == 1){
    m.IFG_theta_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = IFG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.IFG_theta_timebin) == 1){
    m.IFG_theta_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = IFG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.IFG_theta_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.IFG_theta_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_IFG_theta <- bind_rows(coef_IFG_theta,coef_new)
}

slope_IFG_theta <- coef_IFG_theta[seq(0,nrow(coef_IFG_theta),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.IFG_theta <- slope_IFG_theta %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=7, xmax=8, ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  annotate("rect", xmin=15, xmax=16, ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("IFG_theta")+
  theme_classic()
beta.IFG_theta
```

```{r Model pMTG theta}
# pMTG theta linear------
pMTG_theta <- pMTG_theta %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.pMTG_theta <- lmer(corrected_PLV ~ centered_timebin * Condition +
                      (1 | ItemPair) + (1 | Subject) + (1 + Condition | ChannelPair:Subject),
                     data = pMTG_theta, control = lmerControl(optimizer="bobyqa"))
summary(m.pMTG_theta)

## plot model fit
fit.pMTG_theta <- pMTG_theta %>% 
  ggplot(aes(x = TimeBin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.pMTG_theta)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("pMTG_theta")+
  theme_classic()
fit.pMTG_theta

## test assumptions
simulateResiduals(fittedModel = m.pMTG_theta, plot = T)
plot_model(m.pMTG_theta, "diag")
dotplot.ranef.mer(ranef(m.pMTG_theta, condVar=T))

# pMTG theta polynomial------
pMTG_theta <- code_poly(pMTG_theta, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.pMTG_theta3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) +
                       ((poly1 + poly2 + poly3)*Condition | Subject/ChannelPair),
                    data = pMTG_theta, control = lmerControl(optimizer="bobyqa"))
summary(m.pMTG_theta3)

## plot model fit
fit.pMTG_theta3 <- pMTG_theta %>% 
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.pMTG_theta3)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("pMTG_theta3")+
  theme_classic()
fit.pMTG_theta3

## test assumptions
simulateResiduals(fittedModel = m.pMTG_theta3, plot = T)
plot_model(m.pMTG_theta3, "diag")
dotplot.ranef.mer(ranef(m.pMTG_theta3, condVar=T))

# loop pMTG_theta  -------------------------------------------------------
coef_pMTG_theta <- data.frame()
for (i in 6:25){
  pMTG_theta_timebin <- filter(pMTG_theta, TimeBin == i)
  m.pMTG_theta_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = pMTG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.pMTG_theta_timebin) == 1){
    m.pMTG_theta_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = pMTG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.pMTG_theta_timebin) == 1){
    m.pMTG_theta_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = pMTG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.pMTG_theta_timebin) == 1){
    m.pMTG_theta_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = pMTG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
    if (isSingular(m.pMTG_theta_timebin) == 1){
    m.pMTG_theta_timebin <- lmer(corrected_PLV ~ Condition + (1 | ItemPair), 
                              data = pMTG_theta_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.pMTG_theta_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.pMTG_theta_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_pMTG_theta <- bind_rows(coef_pMTG_theta,coef_new)
}
slope_pMTG_theta <- coef_pMTG_theta[seq(0,nrow(coef_pMTG_theta),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.pMTG_theta <- slope_pMTG_theta %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=3, xmax=6,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  annotate("rect", xmin=8, xmax=9,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  annotate("rect", xmin=10, xmax=11,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("pMTG_theta")+
  theme_classic()
beta.pMTG_theta
```

### alpha

```{r Model ATL alpha}
 # ATL alpha linear -------------------------------------------------------
ATL_alpha <- ATL_alpha %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.ATL_alpha <- lmer(corrected_PLV ~ centered_timebin * Condition + 
                      (1 | ItemPair) +(1 | Subject)+ (1 + Condition | ChannelPair:Subject),
                    data = ATL_alpha, REML=T, control = lmerControl(optimizer="bobyqa"))
summary(m.ATL_alpha)

## plot model fit
fit.ATL_alpha <- ATL_alpha %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom= "pointrange", alpha=.5)+
  stat_summary(aes(y = fitted(m.ATL_alpha)), geom="line", size=1.2)+
  geom_hline(yintercept = 0, linetype="dashed")+
  ggtitle("ATL_alpha")+
  theme_bw()
fit.ATL_alpha

## test assumptions
simulateResiduals(fittedModel = m.ATL_alpha, plot = T)
plot_model(m.ATL_alpha, "diag")
dotplot.ranef.mer(ranef(m.ATL_alpha, condVar=T))

# bs1.ATL_theta <- bootstrap(m.ATL_alpha, .f=fixef, type="case", B=100, resample=c(T,F,F))
# bs2.ATL_theta <- bootstrap(m.ATL_alpha, .f=fixef, type="case", B=10, resample=c(F,T,F))


# ATL alpha polynomial -------------------------------------------------------
ATL_alpha <- code_poly(ATL_alpha, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.ATL_alpha3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) +
                       (poly1 + poly2 + Condition | Subject),
                    data = ATL_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.ATL_alpha3)

## plot model fit
fit.ATL_alpha3 <- ATL_alpha %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom= "pointrange", alpha=.5)+
  stat_summary(aes(y = fitted(m.ATL_alpha3)), geom="line", size=1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("ATL_alpha3")+
  theme_bw()
fit.ATL_alpha3

## test assumptions
simulateResiduals(fittedModel = m.ATL_alpha3, plot = T)
plot_model(m.ATL_alpha3, "diag")
dotplot.ranef.mer(ranef(m.ATL_alpha3, condVar=T))

# loop ATL_alpha -------------------------------------------------------
ATL_alpha <- ATL_alpha %>% mutate(ChannelPair = paste(Channel_1, Channel_2, sep = "-"))
coef_ATL_alpha <- data.frame()
for (i in 6:25){
  ATL_alpha_timebin <- filter(ATL_alpha, TimeBin == i)
  m.ATL_alpha_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = ATL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.ATL_alpha_timebin) == 1){
    m.ATL_alpha_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = ATL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.ATL_alpha_timebin) == 1){
    m.ATL_alpha_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = ATL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.ATL_alpha_timebin) == 1){
    m.ATL_alpha_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = ATL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.ATL_alpha_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.ATL_alpha_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_ATL_alpha <- bind_rows(coef_ATL_alpha,coef_new)
}
slope_ATL_alpha <- coef_ATL_alpha[seq(0,nrow(coef_ATL_alpha),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.ATL_alpha <- slope_ATL_alpha %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=7, xmax=8,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  annotate("rect", xmin=10, xmax=11,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("ATL_alpha")+
  theme_classic()
beta.ATL_alpha
```

```{r Model IPL alpha}

# IPL alpha linear -------------------------------------------------------
IPL_alpha <- IPL_alpha %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.IPL_alpha <- lmer(corrected_PLV ~ centered_timebin * Condition + 
                      (1 | ItemPair) +(1 | Subject)+ (1 + Condition | ChannelPair:Subject),
                    data = IPL_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.IPL_alpha)

## plot model fit
fit.IPL_alpha <- IPL_alpha %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom="pointrange", alpha=.5)+
  stat_summary(aes(y = fitted(m.IPL_alpha)), geom="line", size=1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IPL_alpha")+
  theme_bw()
fit.IPL_alpha

## test assumptions
simulateResiduals(fittedModel = m.IPL_alpha, plot = T)
plot_model(m.IPL_alpha, "diag")
dotplot.ranef.mer(ranef(m.IPL_alpha, condVar=T))


# IPL alpha polynomial  -------------------------------------------------------
IPL_alpha <- code_poly(IPL_alpha, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.IPL_alpha3 <- lmer(corrected_PLV ~ (poly1 + poly2 + poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) + (poly1 | Subject),
                    data = IPL_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.IPL_alpha3)

## plot model fit
fit.IPL_alpha3 <- IPL_alpha %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom="pointrange", alpha=.5)+
  stat_summary(aes(y = fitted(m.IPL_alpha3)), geom="line", size=1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IPL_alpha3")+
  theme_bw()
fit.IPL_alpha3

## test assumptions
simulateResiduals(fittedModel = m.IPL_alpha3, plot = T)
plot_model(m.IPL_alpha3, "diag")
dotplot.ranef.mer(ranef(m.IPL_alpha3, condVar=T))

# loop IPL_alpha  -------------------------------------------------------
coef_IPL_alpha <- data.frame()
for (i in 6:25){
  IPL_alpha_timebin <- filter(IPL_alpha, TimeBin == i)
  m.IPL_alpha_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = IPL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.IPL_alpha_timebin) == 1){
    m.IPL_alpha_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = IPL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.IPL_alpha_timebin) == 1){
    m.IPL_alpha_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = IPL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.IPL_alpha_timebin) == 1){
    m.IPL_alpha_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = IPL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.IPL_alpha_timebin) == 1){
    m.IPL_alpha_timebin <- lmer(corrected_PLV ~ Condition + (1 | ItemPair), 
                              data = IPL_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.IPL_alpha_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.IPL_alpha_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_IPL_alpha <- bind_rows(coef_IPL_alpha,coef_new)
}
slope_IPL_alpha <- coef_IPL_alpha[seq(0,nrow(coef_IPL_alpha),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.08, 0, 1))

beta.IPL_alpha <- slope_IPL_alpha %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=11, xmax=12,
           ymin=-.1, ymax=.05, alpha=.7, fill="gray")+
  annotate("rect", xmin=5, xmax=6,
           ymin=-.1, ymax=.05, alpha=.5, fill="gray")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("IPL_alpha")+
  theme_classic()
beta.IPL_alpha
```

```{r Model IFG alpha}
# IFG alpha linear --------------
IFG_alpha <- IFG_alpha %>% 
  mutate(centered_timebin = scale(TimeBin, center=T,scale=F))
m.IFG_alpha <- lmer(corrected_PLV ~ centered_timebin * Condition +
                      (1 | ItemPair) + (1 | Subject) + (1 + Condition | ChannelPair:Subject),
                    data = IFG_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.IFG_alpha)

## plot model fit
fit.IFG_alpha <- IFG_alpha %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.IFG_alpha)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IFG_alpha")+
  theme_bw()
fit.IFG_alpha

## test assumptions
simulateResiduals(fittedModel = m.IFG_alpha, plot = T)
plot_model(m.IFG_alpha, "diag")
dotplot.ranef.mer(ranef(m.IFG_alpha, condVar=T))

# IFG alpha polynomial------
IFG_alpha <- code_poly(IFG_alpha, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.IFG_alpha3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) +
                       ((poly1 + poly2 + poly3)*Condition | Subject/ChannelPair),
                    data = IFG_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.IFG_alpha3)

## plot model fit
fit.IFG_alpha3 <- IFG_alpha %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.IFG_alpha3)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IFG_alpha3")+
  theme_bw()
fit.IFG_alpha3

## test assumptions
simulateResiduals(fittedModel = m.IFG_alpha3, plot = T)
plot_model(m.IFG_alpha3, "diag")
dotplot.ranef.mer(ranef(m.IFG_alpha3, condVar=T))

# loop IFG_alpha  -------------------------------------------------------
coef_IFG_alpha <- data.frame()
for (i in 6:25){
  IFG_alpha_timebin <- filter(IFG_alpha, TimeBin == i)
  m.IFG_alpha_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = IFG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.IFG_alpha_timebin) == 1){
    m.IFG_alpha_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = IFG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.IFG_alpha_timebin) == 1){
    m.IFG_alpha_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = IFG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.IFG_alpha_timebin) == 1){
    m.IFG_alpha_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = IFG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.IFG_alpha_timebin) == 1){
    m.IFG_alpha_timebin <- lmer(corrected_PLV ~ Condition + (1 | ItemPair), 
                              data = IFG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.IFG_alpha_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.IFG_alpha_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_IFG_alpha <- bind_rows(coef_IFG_alpha,coef_new)
}
slope_IFG_alpha <- coef_IFG_alpha[seq(0,nrow(coef_IFG_alpha),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.IFG_alpha <- slope_IFG_alpha %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  ylim(-.1, .07)+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("IFG_alpha")+
  theme_classic()
beta.IFG_alpha
```

```{r Model pMTG alpha}
# pMTG alpha linear-----
pMTG_alpha <- pMTG_alpha %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.pMTG_alpha <- lmer(corrected_PLV ~ centered_timebin*Condition +
                      (1 | ItemPair) + (1 | Subject) + (1 + Condition | ChannelPair:Subject),
                    data = pMTG_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.pMTG_alpha)

## plot model fit
fit.pMTG_alpha <- pMTG_alpha %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.pMTG_alpha)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("pMTG_alpha")+
  theme_bw()
fit.pMTG_alpha

## test assumptions
simulateResiduals(fittedModel = m.pMTG_alpha, plot = T)
plot_model(m.pMTG_alpha, "diag")
dotplot.ranef.mer(ranef(m.pMTG_alpha, condVar=T))

# pMTG alpha polynomial-----
pMTG_alpha <- code_poly(pMTG_alpha, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.pMTG_alpha3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) +
                       ((poly1 + poly2 + poly3)*Condition | Subject/ChannelPair),
                    data = pMTG_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.pMTG_alpha3)

## plot model fit
fit.pMTG_alpha3 <- pMTG_alpha %>% 
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.pMTG_alph3a)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("pMTG_alpha3")+
  theme_bw()
fit.pMTG_alpha3

## test assumptions
simulateResiduals(fittedModel = m.pMTG_alpha3, plot = T)
plot_model(m.pMTG_alpha3, "diag")
dotplot.ranef.mer(ranef(m.pMTG_alpha3, condVar=T))

# loop pMTG_alpha  -------------------------------------------------------
coef_pMTG_alpha <- data.frame()
for (i in 6:25){
  pMTG_alpha_timebin <- filter(pMTG_alpha, TimeBin == i)
  m.pMTG_alpha_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = pMTG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.pMTG_alpha_timebin) == 1){
    m.pMTG_alpha_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = pMTG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.pMTG_alpha_timebin) == 1){
    m.pMTG_alpha_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = pMTG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.pMTG_alpha_timebin) == 1){
    m.pMTG_alpha_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = pMTG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.pMTG_alpha_timebin) == 1){
    m.pMTG_alpha_timebin <- lmer(corrected_PLV ~ Condition + (1 | ItemPair), 
                              data = pMTG_alpha_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.pMTG_alpha_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.pMTG_alpha_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_pMTG_alpha <- bind_rows(coef_pMTG_alpha,coef_new)
}
slope_pMTG_alpha <- coef_pMTG_alpha[seq(0,nrow(coef_pMTG_alpha),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.pMTG_alpha <- slope_pMTG_alpha %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=4, xmax=5,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  annotate("rect", xmin=12, xmax=13,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  annotate("rect", xmin=18, xmax=19,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("pMTG_alpha")+
  theme_classic()
beta.pMTG_alpha
```

### gamma

```{r Model ATL gamma}
# ATL gamma linear -----
ATL_gamma <- ATL_gamma %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.ATL_gamma <- lmer(corrected_PLV ~ centered_timebin * Condition + 
                      (1 | ItemPair) + (1 | Subject)+ (1 + Condition | ChannelPair:Subject),
                    data = ATL_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.ATL_gamma)

## plot model fit
fit.ATL_gamma <- ATL_gamma %>% 
  ggplot(aes(x = centered_timebin, col = Condition))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.ATL_gamma)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("ATL_gamma")+
  theme_bw()
fit.ATL_gamma

## test assumptions
simulateResiduals(fittedModel = m.ATL_gamma, plot = T)
plot_model(m.ATL_gamma, "diag")
dotplot.ranef.mer(ranef(m.ATL_gamma, condVar=T))


# ATL gamma polynomial------
ATL_gamma <- code_poly(ATL_gamma, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.ATL_gamma3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) +
                       (Condition | ChannelPair:Subject)+
                       (poly1 + Condition | Subject),
                    data = ATL_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.ATL_gamma3)

## plot model fit
fit.ATL_gamma3 <- ATL_gamma %>% 
  ggplot(aes(x = centered_timebin, y = corrected_PLV, col = Condition))+
  stat_summary(geom = "pointrange", alpha=.5)+
  stat_summary(aes(y = fitted(m.ATL_gamma3)), geom = "line")+
  geom_hline(yintercept = 0, linetype = "dashed")+
  theme_classic()
fit.ATL_gamma3

## test assumptions
simulateResiduals(fittedModel = m.ATL_gamma3, plot = T)
plot_model(m.ATL_gamma3, "diag")
dotplot.ranef.mer(ranef(m.ATL_gamma3, condVar=T))

# loop ATL gamma ------
coef_ATL_gamma <- data.frame()
for (i in 6:25){
  ATL_gamma_timebin <- filter(ATL_gamma, TimeBin == i)
  m.ATL_gamma_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = ATL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.ATL_gamma_timebin) == 1){
    m.ATL_gamma_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = ATL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.ATL_gamma_timebin) == 1){
    m.ATL_gamma_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = ATL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.ATL_gamma_timebin) == 1){
    m.ATL_gamma_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = ATL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.ATL_gamma_timebin) == 1){
    m.ATL_gamma_timebin <- lmer(corrected_PLV ~ Condition + (1 | ItemPair), 
                              data = ATL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.ATL_gamma_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.ATL_gamma_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_ATL_gamma <- bind_rows(coef_ATL_gamma,coef_new)
}

slope_ATL_gamma <- coef_ATL_gamma[seq(0,nrow(coef_ATL_gamma),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.ATL_gamma <- slope_ATL_gamma %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=8, xmax=10,
           ymin=-.1, ymax=.07, alpha=.3, fill="red")+
  annotate("rect", xmin=14, xmax=15,
           ymin=-.1, ymax=.07, alpha=.3, fill="red")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("ATL_gamma")+
  theme_classic()
beta.ATL_gamma
```

```{r Model IPL gamma}
# IPL gamma linear -----
IPL_gamma <- IPL_gamma %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.IPL_gamma <- lmer(corrected_PLV ~ centered_timebin * Condition + 
                      (1 | ItemPair) + (1 | Subject)+ (1 + Condition | ChannelPair:Subject),
                    data = IPL_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.IPL_gamma)

## plot model fit
fit.IPL_gamma <- IPL_gamma %>% 
  ggplot(aes(x = centered_timebin, y = corrected_PLV, col = Condition))+
  stat_summary(geom = "pointrange", alpha=.5)+
  stat_summary(aes(y = fitted(m.IPL_gamma)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IPL_gamma")+
  theme_bw()
fit.IPL_gamma

## test assumptions
simulateResiduals(fittedModel = m.IPL_gamma, plot = T)
plot_model(m.IPL_gamma, "diag")
dotplot.ranef.mer(ranef(m.IPL_gamma, condVar=T))


# IPL gamma polynomial------
IPL_gamma <- code_poly(IPL_gamma, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.IPL_gamma3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) + (poly1 + poly2 + poly3 | Subject),
                    data = IPL_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.IPL_gamma3)

## plot model fit
fit.IPL_gamma3 <- IPL_gamma %>% 
  ggplot(aes(x = centered_timebin, y = corrected_PLV, col = Condition))+
  stat_summary(geom = "pointrange", alpha=.5)+
  stat_summary(aes(y = fitted(m.IPL_gamma3)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IPL_gamma3")
  theme_classic()
fit.IPL_gamma3

## test assumptions
simulateResiduals(fittedModel = m.IPL_gamma3, plot = T)
plot_model(m.IPL_gamma3, "diag")
dotplot.ranef.mer(ranef(m.IPL_gamma3, condVar=T))


# loop IPL gamma ------
coef_IPL_gamma <- data.frame()
for (i in 6:25){
  IPL_gamma_timebin <- filter(IPL_gamma, TimeBin == i)
  m.IPL_gamma_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = IPL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.IPL_gamma_timebin) == 1){
    m.IPL_gamma_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = IPL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.IPL_gamma_timebin) == 1){
    m.IPL_gamma_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = IPL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.IPL_gamma_timebin) == 1){
    m.IPL_gamma_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = IPL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.IPL_gamma_timebin) == 1){
    m.IPL_gamma_timebin <- lmer(corrected_PLV ~ Condition + (1 | ItemPair), 
                              data = IPL_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.IPL_gamma_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.IPL_gamma_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_IPL_gamma <- bind_rows(coef_IPL_gamma,coef_new)
}

slope_IPL_gamma <- coef_IPL_gamma[seq(0,nrow(coef_IPL_gamma),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.IPL_gamma <- slope_IPL_gamma %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=3, xmax=4,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("IPL_gamma")+
  theme_classic()
beta.IPL_gamma
```

```{r Model IFG gamma}
# IFG gamma linear-----
IFG_gamma <- IFG_gamma %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.IFG_gamma <- lmer(corrected_PLV ~ centered_timebin * Condition +
                      (1 | ItemPair) + (1 | Subject) + (1 + Condition | ChannelPair:Subject),
                    data = IFG_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.IFG_gamma)

## plot model fit
fit.IFG_gamma <- IFG_gamma %>% 
  ggplot(aes(x = centered_timebin, y = corrected_PLV, col = Condition))+
  stat_summary(geom = "pointrange")+
  stat_summary(aes(y = fitted(m.IFG_gamma)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IFG_gamma")+
  theme_bw()
fit.IFG_gamma

## test assumptions
simulateResiduals(fittedModel = m.IFG_gamma, plot = T)
plot_model(m.IFG_gamma, "diag")
dotplot.ranef.mer(ranef(m.IFG_gamma, condVar=T))


# IFG gamma polynomial------
IFG_gamma <- code_poly(IFG_gamma, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.IFG_gamma3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) +
                       ((poly1 + poly2 + poly3)*Condition | Subject/ChannelPair),
                    data = IFG_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.IFG_gamma3)

## plot model fit
fit.IFG_gamma3 <- IFG_gamma %>% 
  ggplot(aes(x = centered_timebin, y = corrected_PLV, col = Condition))+
  stat_summary(geom = "pointrange")+
  stat_summary(aes(y = fitted(m.IFG_gamma3)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("IFG_gamma3")
  theme_classic()
fit.IFG_gamma3

## test assumptions
simulateResiduals(fittedModel = m.IFG_gamma3, plot = T)
plot_model(m.IFG_gamma3, "diag")
dotplot.ranef.mer(ranef(m.IFG_gamma3, condVar=T))


# loop IFG gamma ------
coef_IFG_gamma <- data.frame()
for (i in 6:25){
  IFG_gamma_timebin <- filter(IFG_gamma, TimeBin == i)
  m.IFG_gamma_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = IFG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.IFG_gamma_timebin) == 1){
    m.IFG_gamma_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = IFG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.IFG_gamma_timebin) == 1){
    m.IFG_gamma_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = IFG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.IFG_gamma_timebin) == 1){
    m.IFG_gamma_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = IFG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.IFG_gamma_timebin) == 1){
    m.IFG_gamma_timebin <- lmer(corrected_PLV ~ Condition + (1 | ItemPair), 
                              data = IFG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.IFG_gamma_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.IFG_gamma_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_IFG_gamma <- bind_rows(coef_IFG_gamma,coef_new)
}
slope_IFG_gamma <- coef_IFG_gamma[seq(0,nrow(coef_IFG_gamma),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.IFG_gamma <- slope_IFG_gamma %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=3, xmax=4,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  annotate("rect", xmin=9, xmax=10,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("IFG_gamma")+
  theme_classic()
beta.IFG_gamma
```

```{r Model pMTG gamma}
# pMTG gamma linear ------
pMTG_gamma <- pMTG_gamma %>% 
  mutate(centered_timebin = scale(TimeBin, center=T, scale=F))
m.pMTG_gamma <- lmer(corrected_PLV ~ centered_timebin * Condition +
                      (1 | ItemPair) + (1 | Subject) + (1 + Condition | ChannelPair:Subject),
                    data = pMTG_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.pMTG_gamma)

## plot model fit
fit.pMTG_gamma <- pMTG_gamma %>% 
  ggplot(aes(x = centered_timebin, y = corrected_PLV, col = Condition))+
  stat_summary(geom = "pointrange")+
  stat_summary(aes(y = fitted(m.pMTG_gamma)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("pMTG_gamma")+
  theme_bw()
fit.pMTG_gamma

## test assumptions
simulateResiduals(fittedModel = m.pMTG_gamma, plot = T)
plot_model(m.pMTG_gamma, "diag")
dotplot.ranef.mer(ranef(m.pMTG_gamma, condVar=T))

# pMTG gamma polynomial-----
pMTG_gamma <- code_poly(pMTG_gamma, predictor="TimeBin", poly.order=3, 
                       orthogonal=T, draw.poly=F)
m.pMTG_gamma3 <- lmer(corrected_PLV ~ (poly1+poly2+poly3) * Condition +
                       (poly1 + poly2 + poly3 | ItemPair) +
                       (poly1 + poly2 + poly3 + Condition | Subject),
                    data = pMTG_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.pMTG_gamma3)

## plot model fit
fit.pMTG_gamma3 <- pMTG_gamma %>% 
  ggplot(aes(x = centered_timebin, y = corrected_PLV, col = Condition))+
  stat_summary(geom = "pointrange")+
  stat_summary(aes(y = fitted(m.pMTG_gamma3)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("pMTG_gamma3")
  theme_classic()
fit.pMTG_gamma3

## test assumptions
simulateResiduals(fittedModel = m.pMTG_gamma3, plot = T)
plot_model(m.pMTG_gamma3, "diag")
dotplot.ranef.mer(ranef(m.pMTG_gamma3, condVar=T))

# loop pMTG gamma ------
coef_pMTG_gamma <- data.frame()
for (i in 6:25){
  pMTG_gamma_timebin <- filter(pMTG_gamma, TimeBin == i)
  m.pMTG_gamma_timebin <- lmer(corrected_PLV ~ Condition 
                              + (Condition | Subject/ChannelPair) + (1 | ItemPair), 
                              data = pMTG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
  ranef <- "full"
  if (isSingular(m.pMTG_gamma_timebin) == 1){
    m.pMTG_gamma_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + 
                                (1 | ChannelPair:Subject) + (1 | ItemPair), 
                              data = pMTG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Chl / 1|Trl"
  }
  if (isSingular(m.pMTG_gamma_timebin) == 1){
    m.pMTG_gamma_timebin <- lmer(corrected_PLV ~ Condition + (Condition | Subject) + (1 | ItemPair), 
                              data = pMTG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "Cond|Sub / 1|Trl"
  }
  if (isSingular(m.pMTG_gamma_timebin) == 1){
    m.pMTG_gamma_timebin <- lmer(corrected_PLV ~ Condition + (1 | Subject) +  (1 | ItemPair), 
                              data = pMTG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Sub / 1|Trl"
  }
  if (isSingular(m.pMTG_gamma_timebin) == 1){
    m.pMTG_gamma_timebin <- lmer(corrected_PLV ~ Condition + (1 | ItemPair), 
                              data = pMTG_gamma_timebin, control = lmerControl(optimizer = "bobyqa"))
    ranef <- "1|Trl"
  }
  if (isSingular(m.pMTG_gamma_timebin) == 1){
    ranef <- "-"
  }
  coef_new <- 
    summary(m.pMTG_gamma_timebin)$coefficients %>% 
    data.frame() %>% 
    mutate(TimeBin = i, rand_eff = ranef)
  coef_pMTG_gamma <- bind_rows(coef_pMTG_gamma,coef_new)
}

slope_pMTG_gamma <- coef_pMTG_gamma[seq(0,nrow(coef_pMTG_gamma),2),] %>% 
  mutate(sig = ifelse(Pr...t..>0.05, 0, 1))

beta.pMTG_gamma <- slope_pMTG_gamma %>% 
  ggplot(aes(x=TimeBin-5.5, y=Estimate))+
  annotate("rect", xmin=7, xmax=8,
           ymin=-.1, ymax=.07, alpha=.7, fill="gray")+
  geom_ribbon(aes(ymin=Estimate-Std..Error, ymax=Estimate+Std..Error), fill="#EBE9F8", alpha=.7)+
  geom_line(size = 1.8, col = "#311B92")+
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Time window (100ms)")+
  ylab("Beta (TX-Thm)")+
  ggtitle("pMTG_gamma")+
  theme_classic()
beta.pMTG_gamma
```

```{r plot model fit}
(fit.ATL_theta | fit.IPL_theta | fit.IFG_theta | fit.pMTG_theta)/
  (fit.ATL_alpha | fit.IPL_alpha | fit.IFG_alpha | fit.pMTG_alpha) /
  (fit.ATL_gamma | fit.IPL_gamma | fit.IFG_gamma | fit.pMTG_gamma)

(fit.ATL_theta3 | fit.IPL_theta3) / (fit.ATL_alpha3 | fit.IPL_alpha3) 
  (fit.ATL_alpha3 | fit.IPL_alpha3 | fit.IFG_alpha3 | fit.pMTG_alpha3) /
  (fit.ATL_gamma3 | fit.IPL_gamma3 | fit.IFG_gamma3 | fit.pMTG_gamma3)

(beta.ATL_theta | beta.IPL_theta | beta.IFG_theta | beta.pMTG_theta) / 
  (beta.ATL_alpha | beta.IPL_alpha | beta.IFG_alpha | beta.pMTG_alpha) / 
  (beta.ATL_gamma | beta.IPL_gamma | beta.IFG_gamma | beta.pMTG_gamma)


summary(m.ATL_theta)
summary(m.IPL_theta)
summary(m.IFG_theta)
summary(m.pMTG_theta)

summary(m.ATL_alpha)
summary(m.IPL_alpha)
summary(m.IFG_alpha)
summary(m.pMTG_alpha)

summary(m.ATL_gamma)
summary(m.IPL_gamma)
summary(m.IFG_gamma)
summary(m.pMTG_gamma)

pander(coef(summary(m.ATL_theta)))
pander(coef(summary(m.IPL_theta)))
pander(coef(summary(m.IFG_theta)))
pander(coef(summary(m.pMTG_theta)))

pander(coef(summary(m.ATL_alpha)))
pander(coef(summary(m.IPL_alpha)))
pander(coef(summary(m.IFG_alpha)))
pander(coef(summary(m.pMTG_alpha)))

pander(coef(summary(m.ATL_gamma)))
pander(coef(summary(m.IPL_gamma)))
pander(coef(summary(m.IFG_gamma)))
pander(coef(summary(m.pMTG_gamma)))

tab_model(m.ATL_theta)
```


## Behavioral results

```{r}
filelist.behav <- list.files(".\\behav")
for (i in 1:length(filelist.behav)){
  current_behav <- read.csv(paste0(".\\behav\\", filelist.behav[i]))
  if (i == 1) {
    seeg_behav <- current_behav
  } else {
    seeg_behav <- rbind(seeg_behav, current_behav)
  }
}

seeg_behav_hi <- seeg_behav %>% filter(hilo == "Hi") 
seeg_behav_hi$ACC <- factor(seeg_behav_hi$ACC)
summary(seeg_behav_hi)


substats_txthm <- seeg_behav %>% 
  filter(hilo == "Hi") %>% 
  group_by(Subject, txthm) %>% 
  summarise(RT = mean(RT), 
            ACC = mean(ACC)) 

substats_txthm %>% group_by(txthm) %>%
  summarise(
    mean_RT = mean(RT),
    sd_RT = sd(RT),
    range_RT = range(RT),
    mean_ACC = mean(ACC)*100,
    sd_ACC = sd(ACC)*100,
    range_ACC = range(ACC)*100
  )
substats_txthm2 <- substats_txthm %>% 
  pivot_wider(
    names_from = txthm, values_from = c(RT,ACC)
  )
t.test(Pair(RT_Thm, RT_Tx) ~ 1, data = substats_txthm2)
t.test(Pair(ACC_Thm, ACC_Tx) ~ 1, data = substats_txthm2)
```



```{r model intergrated model}
txthm_theta <- rbind(ATL_theta, IPL_theta)
txthm_alpha <- rbind(ATL_alpha, IPL_alpha)
txthm_gamma <- rbind(ATL_gamma, IPL_gamma)

m.txthm_theta <- lmer(corrected_PLV ~ centered_timebin*Condition*ROI_1+
                      (1 + ROI_1 | ItemPair) +(1 | Subject)+
                      (1 + Condition | ChannelPair:Subject),
                    data = txthm_theta, control = lmerControl(optimizer="bobyqa"))
summary(m.txthm_theta)
pander(coef(summary(m.txthm_theta)))
tab_model(m.txthm_theta)

fit.txthm_theta <- txthm_theta %>% 
  ggplot(aes(x = (TimeBin-5)*100, y = fitted(m.txthm_theta), col = Condition))+
  geom_smooth(aes(linetype = ROI_1, fill = Condition), alpha=.1, method = "lm")+
  scale_color_manual(values=c("brown3","dodgerblue3"))+
  ylab("Corrected PLV")+ggtitle("A")+
  theme_classic()+
  theme(legend.position="none", 
        axis.title.x=element_blank(),
        plot.title=element_text(size=rel(1.5), face="bold"))
fit.txthm_theta


m.txthm_alpha <- lmer(corrected_PLV ~ centered_timebin*Condition*ROI_1+
                      (1 + ROI_1 | ItemPair) +(1 | Subject)+
                      (1 + Condition | ChannelPair:Subject),
                    data = txthm_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.txthm_alpha)
fit.txthm_alpha <- txthm_alpha %>% 
  ggplot(aes(x = (TimeBin-5)*100, y = fitted(m.txthm_alpha), col = Condition))+
  geom_smooth(aes(linetype = ROI_1, fill = Condition), alpha=.1, method = "lm")+
  scale_color_manual(values=c("brown3","dodgerblue3"))+
  ylab("Corrected PLV")+ ggtitle("B")+
  theme_classic()+
  theme(legend.position="none", 
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        plot.title=element_text(size=rel(1.5), face="bold"))
fit.txthm_alpha

m.txthm_gamma <- lmer(corrected_PLV ~ centered_timebin*Condition*ROI_1+
                      (1 + ROI_1 | ItemPair) +(1 | Subject)+
                      (1 + Condition | ChannelPair:Subject),
                    data = txthm_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.txthm_gamma)
fit.txthm_gamma <- txthm_gamma %>% 
  ggplot(aes(x = (TimeBin-5)*100, y = fitted(m.txthm_gamma), col = Condition))+
  geom_smooth(aes(linetype = ROI_1, fill = Condition), alpha=.1, method = "lm")+
  geom_hline(yintercept = 0, linetype = "dashed")+
  scale_color_manual(values=c("brown3","dodgerblue3"))+
  ylab("Corrected PLV")+ ggtitle("C")+
  theme_classic()+
  theme(legend.position="none", 
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        plot.title=element_text(size=rel(1.5), face="bold"))
fit.txthm_gamma

legend <- txthm_gamma %>% 
  ggplot(aes(x = (TimeBin-5)*100, y = fitted(m.txthm_gamma), col = Condition))+
  geom_smooth(aes(linetype = ROI_1, fill = Condition), alpha=.1)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  scale_color_manual(values=c("brown3","dodgerblue3"))+
  xlab("Time")+ ylab("Corrected PLV")+
  ggtitle("C")+
  theme_classic()+
  theme(axis.title.y=element_blank())

fit.txthm_theta | fit.txthm_alpha | fit.txthm_gamma | legend
```


```{r Post hoc t test}
tx_theta <- txthm_theta %>% filter(Condition == "Tx")
thm_theta <- txthm_theta %>% filter(Condition == "Thm")
m.tx_theta <- lmer(corrected_PLV ~ centered_timebin*ROI_1+
                      (1 + ROI_1 | ItemPair) +(1 | Subject)+
                      (1 | ChannelPair:Subject),
                    data = tx_theta, control = lmerControl(optimizer="bobyqa"))
summary(m.tx_theta)
fit.tx_theta <- tx_theta %>% 
  ggplot(aes(x = centered_timebin, col = ROI_1))+
  stat_summary(aes(y = corrected_PLV), geom = "pointrange", alpha = .5)+
  stat_summary(aes(y = fitted(m.tx_theta)), geom = "line", size = 1.2)+
  geom_hline(yintercept = 0, linetype = "dashed")+
  ggtitle("tx_theta")+
  theme_bw()
fit.tx_theta

tx_alpha <- txthm_alpha %>% filter(Condition == "Tx")
thm_alpha <- txthm_alpha %>% filter(Condition == "Thm")
m.tx_alpha <- lmer(corrected_PLV ~ centered_timebin*ROI_1+
                      (1 + ROI_1 | ItemPair) +(1 | Subject)+
                      (1 | ChannelPair:Subject),
                    data = tx_alpha, control = lmerControl(optimizer="bobyqa"))
summary(m.tx_alpha)

tx_gamma <- txthm_gamma %>% filter(Condition == "Tx")
thm_gamma <- txthm_gamma %>% filter(Condition == "Thm")
m.tx_gamma <- lmer(corrected_PLV ~ centered_timebin*ROI_1+
                      (1 + ROI_1 | ItemPair) +(1 | Subject)+
                      (1 | ChannelPair:Subject),
                    data = tx_gamma, control = lmerControl(optimizer="bobyqa"))
summary(m.tx_gamma)


# txATL_theta <- txthm_theta %>% filter(Condition == "Tx" & ROI_1 == "ATL") %>% group_by(ItemPair, TimeBin) %>% summarise(corrected_PLV = mean(corrected_PLV))
# txIPL_theta <- txthm_theta %>% filter(Condition == "Tx" & ROI_1 == "IPL") %>% group_by(ItemPair, TimeBin) %>% summarise(corrected_PLV = mean(corrected_PLV))
# 
# thmATL_theta <- txthm_theta %>% filter(Condition == "Thm" & ROI_1 == "ATL") %>% group_by(ItemPair, TimeBin) %>% summarise(corrected_PLV = mean(corrected_PLV))
# thmIPL_theta <- txthm_theta %>% filter(Condition == "Thm" & ROI_1 == "IPL") %>% group_by(ItemPair, TimeBin) %>% summarise(corrected_PLV = mean(corrected_PLV))
# 
# t.test(txATL_theta$corrected_PLV, txIPL_theta$corrected_PLV)
# t.test(thmATL_theta$corrected_PLV, thmIPL_theta$corrected_PLV)
# t.test(Pair(ACC_Thm, ACC_Tx) ~ 1, data = substats_txthm2)
# 
# lsmeans(object=m.txthm_theta, pairwise ~ Condition * ROI_1, adjust= "tukey")
```





